### ISSUE TITLE
Error in pickling ImageDataGenerator

### ISSUE THREAD

**Issue by eliekawerk** [crazzle/pydata_berlin_2018#1]
Hi there,

Thank you for this nice repo @crazzle 

When trying to execute the code, I get the following error:

INFO: [pid 22201] Worker Worker(salt=060924979, workers=1, host=E-kawerk, username=administrator, pid=22201) running   Configure(config_name=standard)
ERROR: [pid 22201] Worker Worker(salt=060924979, workers=1, host=E-kawerk, username=administrator, pid=22201) failed    Configure(config_name=standard)
Traceback (most recent call last):
  File "/home/administrator/Desktop/pydata_berlin_2018/pydata-luigi/lib/python3.6/site-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/home/administrator/Desktop/pydata_berlin_2018/pydata-luigi/lib/python3.6/site-packages/luigi/worker.py", line 140, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/administrator/Desktop/pydata_berlin_2018/pipelines/00_training_pipeline.py", line 89, in run
    pickle.dump(generator, f) # whatever
TypeError: write() argument must be str, not bytes
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Configure_standard_6a58a4195c   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 5 pending tasks possibly being run by other workers
DEBUG: There are 5 pending tasks unique to this worker
DEBUG: There are 5 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=060924979, workers=1, host=E-kawerk, username=administrator, pid=22201) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 6 tasks of which:
* 1 present dependencies were encountered:
    - 1 ExtractDataset(dataset_version=1, dataset_name=dataset)
* 1 failed:
    - 1 Configure(config_name=standard)
* 4 were left pending, among these:
    * 4 had failed dependencies:
        - 1 BaselineValidation(dataset_version=1, dataset_name=dataset, config_name=standard)
        - 1 Evaluate(...)
        - 1 Export(...)
        - 1 TrainModel(...)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

I tried to change the code in the run method of the Configure class as follows:

with self.output().open("wb") as f:
         pickle.dump(generator, f) 

But I couldn't get it working.

Best,
Elie

**Comment by crazzle** [comment]
Hi Elie!
Damn thanks for the hint :-)!

I will fix it over the weekend.

All the best,
Mark

**Comment by eliekawerk** [comment]
Thanks Mark @crazzle,

I hope you'll be able to present a similar tutorial with airflow anytime soon.

**Comment by poglesbyg** [comment]
HI @crazzle, I'm having this same issue. Any advice on how to get around it? Thanks, Paul

**Comment by crazzle** [comment]
Hi,
it is working now, sorry for the late reply.
There were 2 bugs:
- Dumping a pickled file requires to write a file as binary
- Since a binary target is written, Luigi needs the "no processing" format 
I also added Pillow to the requirements since it seems missing.

Enjoy!
